### ISSUE TITLE
Listy frekwencyjne dla trzymiesięcznych przedziałów

### ISSUE THREAD

**Issue by gkrajewski** [so-sonia/StarWords#2]
Listy frekwencyjne, zarówno form słownikowych, jak i form fleksyjnych, dla kolejnych przedziałów trzymiesięcznych (na razie: może potem zmienimy interwały) ze zdań wziętych z kwestionariusza SiZ wypełnionego dla dzieci 18-36 miesięcy (w praktyce aż do 40). W zamierzeniu ma to pozwolić na identyfikację wyrazów i form fleksyjnych, które pojawiają się dopiero u starszych dzieci.

**Comment by so-sonia** [comment]
Zrobione; w repozytorium pojawiły się 4 pliki: 
 - compare_freq_lemma_max.csv: zawiera listę frekwencyjną form słownikowych; Dla każdego przedziału formy są uszeregowane od najbardziej popularnej do najmniej.
- compare_freq_lemma_by_lemma.csv: zawiera listę frekwencyjną form słownikowych; Każdy wiersz odpowiada jednemu lematowi, a następnie znajdują się częstości występowania (i wśród dzieci) w kolejnych przedziałach wiekowych. Formy są uszeregowane od najbardziej popularnej do najmniej według popularności z przedziału dzieci najstarszych. W tym pliku możemy sprawdzić jak się zmieniała popularność danego lematu, lub w której grupie językowej pojawił się po raz pierwszy.
- compare_freq_tag_max.csv: zawiera listę frekwencyjną form fleksyjnych; Dla każdego przedziału formy są uszeregowane od najbardziej popularnej do najmniej.
- compare_freq_tag_by_tag.csv: zawiera listę frekwencyjną form fleksyjnych; Podobnie jak plik lemma_by_lemma jest uporzadkowany tagami, dla których przypisane są częstości w kolejnych grupach wiekowych

Pliki z tagami ponadto zawierają po trzy przykłady danego tagu. Za każdym razem to są trzy słowa najczęściej używane w danym przedziale wiekowym.
